export const mainScreenCopy = {
  shell: {
    eyebrow: 'Central Parc Immo',
    title: 'Central Parc Immo',
    greeting: 'Bonjour Fabrice',
    accountRole: "Direction d'agence",
    accountContext: 'Reprise de session',
    accountAgency: 'Agence Aubagne',
    accountAvailability: 'Reprise du jour prête',
    orientation: "Sélectionnez une vue pour reprendre votre journée sans perdre le fil des dossiers et relances en cours.",
    workspaceKicker: 'Prise de poste',
    workspaceTitle: 'Espace opérateur',
    workspaceSummary: "Un bureau interne compact pour répartir l'accueil, les dossiers et les relances sans retomber dans un dashboard.",
    collapseNav: 'Réduire le menu',
    expandNav: 'Déplier le menu',
    loading: 'Chargement des données...',
    loadError: 'Impossible de charger les données.',
    noSnapshot: "Aucune donnée n'est disponible pour le moment.",
  },
  navigation: {
    shellLabel: "Navigation de l'application",
    regionLabel: 'Vues de travail',
    home: 'Accueil',
    dossiers: 'Dossiers',
    relances: 'Relances',
  },
  source: {
    regionLabel: 'État des données',
    heading: 'État des données',
    sourceLabel: 'Source active',
    syncedAtLabel: 'Mise à jour',
    filtersLabel: 'Filtres disponibles',
    filtersValue: 'Pôle / Suivi',
    note: "Lecture directe du workbook back-office courant, sans retraitement caché.",
  },
  filters: {
    regionLabel: 'Filtres de travail',
    kicker: 'Vue active',
    heading: 'Contexte de travail',
    description: 'Affinez la vue active avant de reprendre les sujets du jour.',
    poleLabel: 'Pôle',
    poleHelp: 'Limiter la vue à un pôle.',
    statusLabel: 'Suivi',
    statusHelp: 'Afficher les ouverts, à traiter ou préparés.',
  },
  indicators: {
    regionLabel: 'Indicateurs de suivi',
    heading: 'Repères de suivi',
    description: "Des repères courts pour garder le contexte, sans reprendre la main sur la vue active.",
    supportKicker: 'En appui',
    placeholderPill: 'Source à confirmer',
  },
  panels: {
    homeRegionLabel: 'Accueil opérateur',
    dossiersRegionLabel: 'Liste des dossiers',
    relancesRegionLabel: 'Liste des relances',
    sectionKicker: 'Vue active',
    heading: 'Accueil',
    description: "Une page d'entrée plus éditoriale pour relancer les urgences et distribuer la reprise entre dossiers et relances.",
    emptyState: 'Aucune donnée exploitable pour ce filtre.',
    detailRegionLabel: "Détail de l'élément sélectionné",
    detailKicker: 'Élément sélectionné',
    detailHeading: 'Détail',
    detailEmpty: 'Sélectionnez une ligne pour afficher son contexte complet.',
    detailSupportHeading: 'Contexte de traitement',
    detailActivityHeading: 'Activité liée',
    homeSummary: "Une vue d'entrée pour savoir quoi reprendre avant d'ouvrir les piles métier dédiées.",
    dossiersSummary: 'Tous les dossiers visibles dans le contexte courant, avec un détail persistant pour éviter les allers-retours.',
    relancesSummary: 'Les relances en attente et préparées dans une seule vue métier, avec détail persistant.',
    sections: {
      homePriorities: {
        kicker: 'Urgent',
        title: 'Urgences du jour',
        copy: 'Les sujets qui demandent une reprise immédiate.',
      },
      homeDossiers: {
        kicker: 'Dossiers',
        title: 'Dossiers à reprendre',
        copy: "Les dossiers qui demandent encore un suivi actif aujourd'hui.",
      },
      homeRelances: {
        kicker: 'Relances',
        title: 'Relances à reprendre',
        copy: 'Les relances qui doivent être relues, envoyées ou relancées.',
      },
      dossiers: {
        kicker: 'Vue dossiers',
        title: 'Dossiers suivis',
        copy: 'Les dossiers qui doivent rester dans votre champ de travail direct.',
      },
      pendingRelances: {
        kicker: 'Relances',
        title: 'Relances à traiter',
        copy: 'Les relances qui demandent encore une action dans le contexte actif.',
      },
      draftedRelances: {
        kicker: 'Relances',
        title: 'Relances préparées',
        copy: 'Les relances déjà préparées, à relire ou finaliser avant envoi.',
      },
    },
    meta: {
      due: 'Échéance',
      created: 'Créée',
      pole: 'Pôle',
      dossierReference: 'Référence dossier',
      relanceReference: 'Référence relance',
      contact: 'Contact',
      unassigned: 'Non attribué',
      amount: 'Montant',
      invalidSource: 'Valeur source non exploitable',
      notAvailable: 'Non renseigné',
    },
    detailKinds: {
      dossier: 'Dossier suivi',
      relancePending: 'Relance à traiter',
      relanceDrafted: 'Relance préparée',
      priority: 'Priorité du jour',
    },
  },
  workflowLabels: {
    allPoles: 'Tous les pôles',
    allStatuses: 'Tous les suivis',
    open: 'Ouverts',
    pending: 'À traiter',
    drafted: 'Préparées',
  },
  states: {
    actionNeeded: 'À traiter',
    overdue: 'En retard',
    recent: 'Récente',
    drafted: 'Préparée',
    routine: 'Suivi courant',
    emptyRelance: 'Suivi de relance',
    pendingRelance: 'Relance à traiter',
    draftedRelance: 'Relance préparée',
  },
  kpis: {
    openDossiers: {
      title: 'Dossiers ouverts',
      note: 'Dossiers visibles et encore ouverts dans le contexte actif.',
    },
    pendingRelances: {
      title: 'Relances à traiter',
      note: 'Relances encore en attente dans le contexte actif.',
    },
    draftedRelances: {
      title: 'Relances préparées',
      note: 'Relances déjà préparées et visibles dans le contexte actif.',
    },
    actionNeeded: {
      title: 'Priorités du jour',
      note: 'Éléments à reprendre maintenant ou déjà en retard.',
    },
    recentActivity: {
      title: 'Activité récente',
      note: 'Dossiers et relances ajoutés récemment dans le contexte actif.',
    },
    comingSoon: {
      title: 'Indicateurs à venir',
      value: 'À venir',
      note: 'Budgets, lots, croissance et délais resteront explicites tant que les sources ne sont pas confirmées.',
      source: 'Source à confirmer',
    },
  },
} as const;
